/**
 * Created by Insolia on 19.02.17.
 */

PAGE_TITLE = "Memory Pinball";

CODE_EMPTY_CELL = "E";
CODE_LEFT_WALL = "L";
CODE_RIGHT_WALL = "R";

CODE_RIGHT_BORDER = "BR";
CODE_LEFT_BORDER = "BL";
CODE_TOP_BORDER = "BT";
CODE_BOTTOM_BORDER = "BB";
CODE_CORNER_BORDER = "BC";

BORDER_CODES = [CODE_RIGHT_BORDER,CODE_LEFT_BORDER,CODE_TOP_BORDER,CODE_BOTTOM_BORDER,CODE_CORNER_BORDER];

HTML_CELL = '<td> <img src="{{pic_address}}" class="cell" id="{{cell_id}}"> </td>';
HTML_BORDER = '<td> <img src="{{pic_address}}" class="border" id="{{border_id}}"> </td>';


PIC_ADRESS_EMPTY = 'resources/files/sq.jpg';
PIC_ADRESS_LEFT_WALL  = 'resources/files/sq.jpg';
PIC_ADRESS_RIGHT_WALL = 'resources/files/sq.jpg';

PIC_ADRESS_RIGHT_BORDER = 'resources/files/sq.jpg';
PIC_ADRESS_LEFT_BORDER = 'resources/files/sq.jpg';
PIC_ADRESS_TOP_BORDER = 'resources/files/sq.jpg';
PIC_ADRESS_BOTTOM_BORDER = 'resources/files/sq.jpg';
PIC_ADRESS_CORNER_BORDER = 'resources/files/sq.jpg';


CODE_PIC_MAP = {};
CODE_PIC_MAP[CODE_EMPTY_CELL] = PIC_ADRESS_EMPTY;
CODE_PIC_MAP[    CODE_LEFT_WALL]= PIC_ADRESS_LEFT_WALL;
CODE_PIC_MAP[CODE_RIGHT_WALL ]= PIC_ADRESS_RIGHT_WALL;
CODE_PIC_MAP[CODE_RIGHT_BORDER ]= PIC_ADRESS_RIGHT_BORDER;
CODE_PIC_MAP[CODE_LEFT_BORDER]= PIC_ADRESS_LEFT_BORDER;
CODE_PIC_MAP[CODE_TOP_BORDER]=PIC_ADRESS_TOP_BORDER;
CODE_PIC_MAP[CODE_BOTTOM_BORDER]=PIC_ADRESS_BOTTOM_BORDER;
CODE_PIC_MAP[CODE_CORNER_BORDER] = PIC_ADRESS_CORNER_BORDER;

